version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    environment:
      - VITE_CLIENT_ID=${CLIENT_ID}
      - VITE_REACT_REDIRECT=${REACT_REDIRECT}
      - VITE_API_BASE_URL=${API_BASE_URL}
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
    restart: unless-stopped